GET http://localhost:3000/movie/3

###

POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Karen",
  "last_name": "Schuareamer",
  "known_for": "her moms basement",
  "age": 40,
  "movie_id": 2
}

###

GET http://localhost:3000/actors/

###

PATCH http://localhost:3000/actors/2
Content-Type: application/json

{
  "gender": "male",
  "age": 45
}

###

DELETE http://localhost:3000/actors/5

###

GET http://localhost:3000/movies

###

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Grinch",
  "year": "2018",
  "plot": "A story of a cynical grump who goes on a mission to steal Christmas, only to have his heart changed by a young girl's generous holiday spirit."
}

###

GET http://localhost:3000/movies/1

###

PATCH http://localhost:3000/movies/1
Content-Type: application/json

{
  "image_url": "https://m.media-amazon.com/images/M/MV5BMTQ2MzYwMzk5Ml5BMl5BanBnXkFtZTcwOTI4NzUyMw@@._V1_.jpg"
}

### CREATE USER

### Users create (signup)
POST http://localhost:3000/users
Content-Type: application/json

{
  "name": "Psyko",
  "email": "psyko@gmail.com",
  "password": "password",
  "password_confirmation": "password"
}

### CREATE 

POST http://localhost:3000/movie_genres
Content-Type: application/json

{
  "movie_id": 7,
  "genre_id": 3
}

###CREATE SESSION
POST http://localhost:3000/sessions
Content-Type: application/json

{
  "email": "zia@gmail.com",
  "password": "password"
}

