GET http://localhost:3000/movie/3

###

POST http://localhost:3000/actors
Content-Type: application/json

{
  "first_name": "Ryan",
  "last_name": "Gosling",
  "known_for": "The Notebook"
}

###

GET http://localhost:3000/actors/6

###

PATCH http://localhost:3000/actors/2
Content-Type: application/json

{
  "movie_id": 7
}

###

DELETE http://localhost:3000/actors/5

###

GET http://localhost:3000/movies

###

POST http://localhost:3000/movies
Content-Type: application/json

{
  "title": "The Grinch",
  "year": "2018",
  "plot": "A story of a cynical grump who goes on a mission to steal Christmas, only to have his heart changed by a young girl's generous holiday spirit."
}

###

GET http://localhost:3000/movies/3

###

PATCH http://localhost:3000/movies/7
Content-Type: application/json

{
  "plot": "Ron Burgundy is San Diego's top-rated newsman in the male-dominated broadcasting of the 1970s, but that's all about to change for Ron and his cronies when an ambitious woman is hired as a new anchor."
}

###

